In [1]:
import pandas as pd
import os

In [2]:
df_final = pd.read_csv("C:/Users/Santiago/OneDrive - Universidad EAFIT/Documents/EAFIT/CAOBA/PROYECTO_INTEGRADOR_2025II/DATA/PROCESSED/key_merged.csv", sep=";", encoding="latin1")
df_final.head()

C:\Users\Santiago\AppData\Local\Temp\ipykernel_19452\1086905009.py:1: DtypeWarning: Columns (96,111) have mixed types. Specify dtype option on import or set low_memory=False.
  df_final = pd.read_csv("C:/Users/Santiago/OneDrive - Universidad EAFIT/Documents/EAFIT/CAOBA/PROYECTO_INTEGRADOR_2025II/DATA/PROCESSED/key_merged.csv", sep=";", encoding="latin1")

,primary_key,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,...,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S9,P5222S10,P5222S8A1,P6008
0,73090601,20230104,1,2023,7309060,1,1,1,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
1,73090601,20230104,1,2023,7309060,1,2,1,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
2,73090601,20230104,1,2023,7309060,1,3,1,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
3,73090611,20230104,1,2023,7309061,1,1,1,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
4,73090611,20230104,1,2023,7309061,1,2,1,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0

In [3]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 860802 entries, 0 to 860801
Columns: 113 entries, primary_key to P6008
dtypes: float64(78), int64(31), object(4)
memory usage: 742.1+ MB

In [4]:
df_final.shape

(860802, 113)

In [5]:
df_final['key_ninos'] = df_final['primary_key'].astype(str) + "" + df_final['ORDEN'].astype(str)
columns = ['key_ninos'] + [col for col in df_final.columns if col != 'key_ninos']
df_final = df_final[columns]
df_final.head()

,key_ninos,primary_key,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,...,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S9,P5222S10,P5222S8A1,P6008
0,730906011,73090601,20230104,1,2023,7309060,1,1,1,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
1,730906012,73090601,20230104,1,2023,7309060,1,2,1,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
2,730906013,73090601,20230104,1,2023,7309060,1,3,1,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
3,730906111,73090611,20230104,1,2023,7309061,1,1,1,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
4,730906112,73090611,20230104,1,2023,7309061,1,2,1,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0

In [14]:
df_ninos = pd.read_csv("C:/Users/Santiago/Downloads/ninos.CSV", sep=";", encoding="latin1")
df_ninos.head()

,DIRECTORIO,SECUENCIA_P,TAM_HOGAR,ORDEN,P3271,P6040,P6050,P6070,P6090,P6100,...,P3503S2,P3504,P3504S1,P3504S2,P423,RAMA4D_R4,RAMA2D_R4,FEX_C,AREA,OFICIO_C8
0,7567356,1,5,3,2,15,3,6.0,1,1.0,...,NaN,2,NaN,NaN,NaN,NaN,NaN,468.040280,5,NaN
1,7567356,1,5,4,1,8,3,NaN,1,1.0,...,NaN,2,NaN,NaN,NaN,NaN,NaN,468.040280,5,NaN
2,7567356,1,5,5,2,5,3,NaN,1,1.0,...,NaN,2,NaN,NaN,NaN,NaN,NaN,468.040280,5,NaN
3,7567358,1,4,4,2,16,3,4.0,1,3.0,...,NaN,2,NaN,NaN,NaN,NaN,NaN,397.972682,5,NaN
4,7567360,1,4,3,1,6,8,NaN,1,3.0,...,NaN,2,NaN,NaN,NaN,NaN,NaN,490.101120,5,NaN

In [15]:
df_ninos['key_ninos'] = df_ninos['DIRECTORIO'].astype(str) + "" + df_ninos['SECUENCIA_P'].astype(str) + "" + df_ninos['ORDEN'].astype(str)
columns = ['key_ninos'] + [col for col in df_ninos.columns if col != 'key_ninos']
df_ninos = df_ninos[columns]
df_ninos.head()

,key_ninos,DIRECTORIO,SECUENCIA_P,TAM_HOGAR,ORDEN,P3271,P6040,P6050,P6070,P6090,...,P3503S2,P3504,P3504S1,P3504S2,P423,RAMA4D_R4,RAMA2D_R4,FEX_C,AREA,OFICIO_C8
0,756735613,7567356,1,5,3,2,15,3,6.0,1,...,NaN,2,NaN,NaN,NaN,NaN,NaN,468.040280,5,NaN
1,756735614,7567356,1,5,4,1,8,3,NaN,1,...,NaN,2,NaN,NaN,NaN,NaN,NaN,468.040280,5,NaN
2,756735615,7567356,1,5,5,2,5,3,NaN,1,...,NaN,2,NaN,NaN,NaN,NaN,NaN,468.040280,5,NaN
3,756735814,7567358,1,4,4,2,16,3,4.0,1,...,NaN,2,NaN,NaN,NaN,NaN,NaN,397.972682,5,NaN
4,756736013,7567360,1,4,3,1,6,8,NaN,1,...,NaN,2,NaN,NaN,NaN,NaN,NaN,490.101120,5,NaN

In [16]:
df_ninos.shape

(42572, 133)

In [17]:
df_final.shape

(860802, 114)

In [18]:
df_merged = pd.merge(df_final, df_ninos, on='key_ninos', how='left')
df_merged.head()

,key_ninos,primary_key,PERIODO,MES,PER,DIRECTORIO_x,SECUENCIA_P_x,ORDEN_x,HOGAR,REGIS,...,P3503S2,P3504,P3504S1,P3504S2,P423,RAMA4D_R4,RAMA2D_R4,FEX_C,AREA_y,OFICIO_C8
0,730906011,73090601,20230104,1,2023,7309060,1,1,1,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,730906012,73090601,20230104,1,2023,7309060,1,2,1,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,730906013,73090601,20230104,1,2023,7309060,1,3,1,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,730906111,73090611,20230104,1,2023,7309061,1,1,1,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,730906112,73090611,20230104,1,2023,7309061,1,2,1,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df_merged.shape

(860802, 246)